FROM ruby:3.2.2-bullseye

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
ENV APP_ROOT /okamemo_app

RUN mkdir $APP_ROOT
WORKDIR $APP_ROOT

COPY Gemfile $APP_ROOT/Gemfile
COPY Gemfile.lock $APP_ROOT/Gemfile.lock

RUN apt-get update -qq\
  && apt-get install -yq --no-install-recommends\
    build-essential \
    libcurl4-openssl-dev \
    libmariadb-dev \
    tzdata \
    less \
    vim \
  && apt-get clean \
  && rm -rf /var/cache/apt/archives/* \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && truncate -s 0 /var/log/*log

RUN gem install bundler -v 2.4.15
RUN bundle -v \
  && bundle install

COPY . $APP_ROOT

COPY ./docker/app/entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT [ "entrypoint.sh" ]

RUN bundle config set --local path 'vendor/bundle'

CMD ["sh", "./docker/app/start-server.sh"]
