FROM --platform=linux/x86_64 nginx:mainline-bullseye

RUN rm -f /etc/nginx/conf.d/*

COPY ./docker/web_prod/nginx.prod.conf /etc/nginx/nginx.conf

CMD /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
