services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.dev
    volumes:
      - .:/okamemo_app
      - vendor_bundle:/okamemo_app/vendor/bundle
      - public_data:/okamemo_app/public
      - tmp_data:/okamemo_app/tmp
    depends_on:
      - db
      - redis
      - selenium_chrome
    stdin_open: true
    tty: true
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s"
  db:
    image: mysql:8.0.46
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '33066:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile.dev
    volumes:
      - ./docker/web/nginx.dev.conf:/etc/nginx/nginx.conf
      - public_data:/okamemo_app/public
      - tmp_data:/okamemo_app/tmp
    ports:
      - '80:80'
    depends_on:
      - app
  redis:
    image: redis:bullseye
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
  sidekiq:
    build:
      context: .
      dockerfile: ./docker/sidekiq/Dockerfile.dev
    volumes:
      - .:/okamemo_app
    depends_on:
      - db
      - redis
  selenium_chrome:
    image: selenium/standalone-chromium:131.0
    platform: linux/arm64
    shm_size: 256m
    ports:
      - '4444:4444'

volumes:
  mysql_data:
  vendor_bundle:
  tmp_data:
  public_data:
  redis:
