services:
  app:
    build:
      context: .
      dockerfile: ./docker/app_ci/Dockerfile.ci
    container_name: app
    volumes:
      - .:/okamemo_app
    depends_on:
      - db
      - selenium_chrome
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
      # テストに必要な環境変数を設定（ダミーの値を使用する）
      ADMIN_USER_EMAIL: master_admin_user@example.test
      HASHID_SALT_CHAR: test_hashid_salt
      CONTACT_EMAIL: contact_email@example.test
      GOOGLE_MAP_API_KEY: dummy_google_map_api_key
    ports:
      - '3000:3000'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s"
  db:
    image: mysql:8.0.46
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '33066:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  selenium_chrome:
    image: selenium/standalone-chrome:131.0
    shm_size: 256m
    ports:
      - '4444:4444'
